treatments:
  - name: solo 5 feedback long
    factorIds:
      - YWwosMevTALbyZmjc
      - Z8qTZzDedy9mqYYhY
      - PQvnpuGXvAbpdSAg7
      - Ciqz88yG78NNW7axH
      - qtgWqpEtizZ4SKF5C
      - 8xBkmBYw37fmy9Ztb
      - oWBpWDi7Bp2MysKkg
      - HtyBPSwcDcFZiGLvJ
      - tJmZu4H8sbYRjXiuK
      - MaG95p6XpuhAcDuyv
      - 4iyZdsK3HiRFWYcdi
  - name: multiplayer_3 feedback long
    factorIds:
      - p6nwB2WcgooiR5f7b
      - Z8qTZzDedy9mqYYhY
      - PQvnpuGXvAbpdSAg7
      - Ciqz88yG78NNW7axH
      - qtgWqpEtizZ4SKF5C
      - 8xBkmBYw37fmy9Ztb
      - AAXBytkKFMDyadCH9
      - oWBpWDi7Bp2MysKkg
      - HtyBPSwcDcFZiGLvJ
      - tJmZu4H8sbYRjXiuK
      - MaG95p6XpuhAcDuyv
      - 4iyZdsK3HiRFWYcdi
      - 2duLyYvaQhewWps8x
      - o8zYCvwLka2rwDgfX
      - qGAvofMccGriujk7W
factorTypes:
  - _id: juXd9nXMj8iiotuBM
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: sToqhgYZPejDWvsp9
    name: nRounds
    description: number of round
    required: true
    type: Integer
    min: 0
  - _id: wz7s4ufXj2ss5hHGY
    name: randomizeTask
    description: Randomize task
    required: false
    type: Boolean
  - _id: GCGbdjiqFbsHYAYSk
    name: feedback
    description: Feedback
    required: false
    type: Boolean
  - _id: iw8PeJ2CMPbzWhjjZ
    name: feedbackDuration
    description: Feedback duration
    required: false
    type: Number
  - _id: TiwWcki7aj5rS7PvN
    name: responseDuration
    description: Response stage duration in seconds
    required: true
    type: Integer
    min: 1
    max: 1000000000000000
  - _id: yyF4hBsuajGDxxfYP
    name: taskType
    description: >-
      Should be a comma-separated list of task types to use. If not given, all
      task types will be used.
    required: false
    type: String
  - _id: hYW2mT46onSdYX7ds
    name: basePay
    description: >-
      The base amount of money (in USD) a user will get from completing the
      experiment.
    required: true
    type: Number
    min: 0
    max: 10000
  - _id: yfzad3ndbNLQvp8BA
    name: conversionRate
    description: >-
      The conversion rate of score to bonus dollars paid: points x
      conversionRate = bonus in USD.
    required: false
    type: Number
    min: 0
    max: 100000
  - _id: YMa7vmBFmum5YcHX4
    name: longTermEngagement
    description: >-
      For conditions that don’t require synchronized gameplay between multiple
      users/clients; determines whether an additional stage will be added to the
      end of each round with maximum/infinite duration, allowing users to leave
      and return to the page at their convenience.
    required: false
    type: Boolean
  - _id: pGbLrSrHZAatHoC9K
    name: quitEarly
    description: >-
      If toggled, a subject has the option to skip to the Exit Steps prior to
      starting a new round.
    required: false
    type: Boolean
  - _id: KPaBsT8QA6WWc8osT
    name: hints
    description: >-
      Determines what percentage of players will receive hints for their
      questions. This is a JSON map for player index to an array of hint indexes
      that describes exactly which hints are available to which player. If a
      player is not defined they have no hints, if no hints are defined at all,
      all players see all hints. E.g. { "1": [1,2], "2": [2,3], "4": [2]...}
    required: false
    type: String
  - _id: nB5HyfYmdxKQzWkyi
    name: revealHints
    description: Allows to set the hints as directly revealed.
    required: false
    type: Boolean
  - _id: LqbnLgDHgJzprHbAR
    name: chat
    description: >-
      Determines whether or not you can chat with your neighbors during the
      interactive stage.
    required: true
    type: Boolean
  - _id: mJ3zD5ewQTKtQDmhh
    name: interactionMode
    description: >-
      Determines what kind of interactions the user will be capable of. This
      will either be continuous (each player will be able to see their
      neighbors’ real-time changes) or discreet (players will only be allowed to
      see their neighbors’ guesses after the stage is done).
    required: true
    type: String
    min: 1
    max: 999999
factors:
  - _id: PQvnpuGXvAbpdSAg7
    name: 'true'
    value: true
    factorTypeId: wz7s4ufXj2ss5hHGY
  - _id: Sa26HotHjhxehMcvj
    name: 'false'
    value: false
    factorTypeId: wz7s4ufXj2ss5hHGY
  - _id: Ciqz88yG78NNW7axH
    name: 'true'
    value: true
    factorTypeId: GCGbdjiqFbsHYAYSk
  - _id: rkncxD86QhKGKTjtf
    name: 'false'
    value: false
    factorTypeId: GCGbdjiqFbsHYAYSk
  - _id: tJmZu4H8sbYRjXiuK
    name: 'true'
    value: true
    factorTypeId: YMa7vmBFmum5YcHX4
  - _id: kFaEeY9xcaeJCYo7g
    name: 'false'
    value: false
    factorTypeId: YMa7vmBFmum5YcHX4
  - _id: MaG95p6XpuhAcDuyv
    name: 'true'
    value: true
    factorTypeId: pGbLrSrHZAatHoC9K
  - _id: tAkriX9BDRQFTBmBi
    name: 'false'
    value: false
    factorTypeId: pGbLrSrHZAatHoC9K
  - _id: 2duLyYvaQhewWps8x
    name: 'true'
    value: true
    factorTypeId: nB5HyfYmdxKQzWkyi
  - _id: mRAkn88bQLWRmXYyK
    name: 'false'
    value: false
    factorTypeId: nB5HyfYmdxKQzWkyi
  - _id: YWwosMevTALbyZmjc
    name: '1'
    value: 1
    factorTypeId: juXd9nXMj8iiotuBM
  - _id: Z8qTZzDedy9mqYYhY
    name: '5'
    value: 5
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: Sqr54q2XogC8senCu
    name: '10'
    value: 10
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: qtgWqpEtizZ4SKF5C
    name: 30s
    value: 30
    factorTypeId: iw8PeJ2CMPbzWhjjZ
  - _id: 8xBkmBYw37fmy9Ztb
    name: 30s
    value: 30
    factorTypeId: TiwWcki7aj5rS7PvN
  - _id: HtyBPSwcDcFZiGLvJ
    name: 1to1
    value: 1
    factorTypeId: yfzad3ndbNLQvp8BA
  - _id: oWBpWDi7Bp2MysKkg
    name: 1USD
    value: 1
    factorTypeId: hYW2mT46onSdYX7ds
  - _id: AAXBytkKFMDyadCH9
    name: geopolitics_daily_life_facts
    value: 'geopolitics,daily_life_facts'
    factorTypeId: yyF4hBsuajGDxxfYP
  - _id: 4iyZdsK3HiRFWYcdi
    name: somehints
    value: '{ "1": [1,2], "2": [2,3], "4": [2]}'
    factorTypeId: KPaBsT8QA6WWc8osT
  - _id: AtNbG3cX6WPS5gRQY
    name: '45'
    value: 45
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: p6nwB2WcgooiR5f7b
    name: '3'
    value: 3
    factorTypeId: juXd9nXMj8iiotuBM
  - _id: o8zYCvwLka2rwDgfX
    name: 'true'
    value: true
    factorTypeId: LqbnLgDHgJzprHbAR
  - _id: mmYdxtZ76G9jCngqC
    name: 'false'
    value: false
    factorTypeId: LqbnLgDHgJzprHbAR
  - _id: d8g6RFXEof6HrRm3g
    name: discreet
    value: discreet
    factorTypeId: mJ3zD5ewQTKtQDmhh
  - _id: 3BvaoebRSHSMNnSYE
    name: continous
    value: continous
    factorTypeId: mJ3zD5ewQTKtQDmhh
    archivedAt: 2021-02-03T05:12:58.454Z
  - _id: qGAvofMccGriujk7W
    name: continuous
    value: continuous
    factorTypeId: mJ3zD5ewQTKtQDmhh
lobbyConfigs:
  - name: Default
    timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: fail
    gameLobbyIds: []
  - name: NeverFail
    timeoutType: lobby
    timeoutInSeconds: 3600000
    timeoutStrategy: fail
    gameLobbyIds: []
