treatments:
  - name: solo 5 feedback long
    factorIds:
      - YWwosMevTALbyZmjc
      - Z8qTZzDedy9mqYYhY
      - kiKcJfJTFANqW2Z6g
      - bnxoQJ6wHvM4Zm8sd
      - qtgWqpEtizZ4SKF5C
      - 8xBkmBYw37fmy9Ztb
      - oWBpWDi7Bp2MysKkg
      - HtyBPSwcDcFZiGLvJ
      - X5QksjWTyCb26JJip
      - kp2Wg59FePepAvNjk
      - 4iyZdsK3HiRFWYcdi
factorTypes:
  - _id: YESkX9Jmf59uKrxhd
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: sToqhgYZPejDWvsp9
    name: nRounds
    description: number of round
    required: true
    type: Integer
    min: 0
  - _id: wz7s4ufXj2ss5hHGY
    name: randomizeTask
    description: Randomize task
    required: false
    type: Boolean
  - _id: GCGbdjiqFbsHYAYSk
    name: feedback
    description: Feedback
    required: false
    type: Boolean
  - _id: iw8PeJ2CMPbzWhjjZ
    name: feedbackDuration
    description: Feedback duration
    required: false
    type: Number
  - _id: TiwWcki7aj5rS7PvN
    name: responseDuration
    description: Response stage duration in seconds
    required: true
    type: Integer
    min: 1
    max: 1000000000000000
  - _id: yyF4hBsuajGDxxfYP
    name: taskType
    description: >-
      Should be a comma-separated list of task types to use. If not given, all
      task types will be used.
    required: false
    type: String
  - _id: hYW2mT46onSdYX7ds
    name: basePay
    description: >-
      The base amount of money (in USD) a user will get from completing the
      experiment.
    required: true
    type: Number
    min: 0
    max: 10000
  - _id: yfzad3ndbNLQvp8BA
    name: conversionRate
    description: >-
      The conversion rate of score to bonus dollars paid: points x
      conversionRate = bonus in USD.
    required: false
    type: Number
    min: 0
    max: 100000
  - _id: YMa7vmBFmum5YcHX4
    name: longTermEngagement
    description: >-
      For conditions that don’t require synchronized gameplay between multiple
      users/clients; determines whether an additional stage will be added to the
      end of each round with maximum/infinite duration, allowing users to leave
      and return to the page at their convenience.
    required: false
    type: Boolean
  - _id: pGbLrSrHZAatHoC9K
    name: quitEarly
    description: >-
      If toggled, a subject has the option to skip to the Exit Steps prior to
      starting a new round.
    required: false
    type: Boolean
  - _id: KPaBsT8QA6WWc8osT
    name: hints
    description: >-
      Determines what percentage of players will receive hints for their
      questions. This is a JSON map for player index to an array of hint indexes
      that describes exactly which hints are available to which player. If a
      player is not defined they have no hints, if no hints are defined at all,
      all players see all hints. E.g. { "1": [1,2], "2": [2,3], "4": [2]...}
    required: false
    type: String
factors:
  - _id: kiKcJfJTFANqW2Z6g
    name: "true"
    value: true
    factorTypeId: wz7s4ufXj2ss5hHGY
  - _id: Z6f7TS5PJcrg7K9HX
    name: "false"
    value: false
    factorTypeId: wz7s4ufXj2ss5hHGY
  - _id: bnxoQJ6wHvM4Zm8sd
    name: "true"
    value: true
    factorTypeId: GCGbdjiqFbsHYAYSk
  - _id: Kij3tW4fAoM8tzr5S
    name: "false"
    value: false
    factorTypeId: GCGbdjiqFbsHYAYSk
  - _id: X5QksjWTyCb26JJip
    name: "true"
    value: true
    factorTypeId: YMa7vmBFmum5YcHX4
  - _id: vqsuP8ezetDJTs96Z
    name: "false"
    value: false
    factorTypeId: YMa7vmBFmum5YcHX4
  - _id: kp2Wg59FePepAvNjk
    name: "true"
    value: true
    factorTypeId: pGbLrSrHZAatHoC9K
  - _id: CZxqY2a2pdp5e7mDf
    name: "false"
    value: false
    factorTypeId: pGbLrSrHZAatHoC9K
  - _id: YWwosMevTALbyZmjc
    name: "1"
    value: 1
    factorTypeId: YESkX9Jmf59uKrxhd
  - _id: Z8qTZzDedy9mqYYhY
    name: "5"
    value: 5
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: Sqr54q2XogC8senCu
    name: "10"
    value: 10
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: qtgWqpEtizZ4SKF5C
    name: 30s
    value: 30
    factorTypeId: iw8PeJ2CMPbzWhjjZ
  - _id: 8xBkmBYw37fmy9Ztb
    name: 30s
    value: 30
    factorTypeId: TiwWcki7aj5rS7PvN
  - _id: HtyBPSwcDcFZiGLvJ
    name: 1to1
    value: 1
    factorTypeId: yfzad3ndbNLQvp8BA
  - _id: oWBpWDi7Bp2MysKkg
    name: 1USD
    value: 1
    factorTypeId: hYW2mT46onSdYX7ds
  - _id: AAXBytkKFMDyadCH9
    name: geopolitics_daily_life_facts
    value: "geopolitics,daily_life_facts"
    factorTypeId: yyF4hBsuajGDxxfYP
  - _id: 4iyZdsK3HiRFWYcdi
    name: somehints
    value: '{ "1": [1,2], "2": [2,3], "4": [2]}'
    factorTypeId: KPaBsT8QA6WWc8osT
lobbyConfigs:
  - name: Default
    timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: fail
    gameLobbyIds: []
  - name: NeverFail
    timeoutType: lobby
    timeoutInSeconds: 3600000
    timeoutStrategy: fail
    gameLobbyIds: []
