treatments:
  - name: solo 5 feedback long
    factorIds:
      - YWwosMevTALbyZmjc
      - Z8qTZzDedy9mqYYhY
      - ArL63u3q64JMufmWJ
      - TBiHZfwFejWkukJfc
      - qtgWqpEtizZ4SKF5C
      - 8xBkmBYw37fmy9Ztb
      - oWBpWDi7Bp2MysKkg
      - HtyBPSwcDcFZiGLvJ
      - TGWHdjXXjZLwccjdw
      - xL3AGrYLngXBjWxqp
      - 4iyZdsK3HiRFWYcdi
  - name: multi3
    factorIds:
      - p6nwB2WcgooiR5f7b
      - Z8qTZzDedy9mqYYhY
      - ArL63u3q64JMufmWJ
      - TBiHZfwFejWkukJfc
      - qtgWqpEtizZ4SKF5C
      - 8xBkmBYw37fmy9Ztb
      - AAXBytkKFMDyadCH9
      - oWBpWDi7Bp2MysKkg
      - HtyBPSwcDcFZiGLvJ
      - ZXvRriwSMpEidbM4E
      - b8i6PkgHkEfsjJ7uN
      - 4iyZdsK3HiRFWYcdi
      - 7QscstLbRakw44Wwv
      - 6bzoJXgwpMBrHLAxH
      - d8g6RFXEof6HrRm3g
      - iQFwSueW7AupfFpGu
      - tPTgyDJuhEMqPfMcK
      - 5SpR3Kt6gjPX3zHLc
      - J5jNLC9t5qCucCsYr
      - mRAjBBhgpWThngkRH
      - wet8mjby3Yb7a6EQW
      - BYeSsSwkoAHyh6tJb
      - ZATTb3q7sXwZDzmM3
      - tz95WfetfCbBPhpqw
  - name: 4players_discreet
    factorIds:
      - 3rBswLaaDosuk8nBx
      - Z8qTZzDedy9mqYYhY
      - ArL63u3q64JMufmWJ
      - TBiHZfwFejWkukJfc
      - qtgWqpEtizZ4SKF5C
      - 8xBkmBYw37fmy9Ztb
      - AAXBytkKFMDyadCH9
      - oWBpWDi7Bp2MysKkg
      - HtyBPSwcDcFZiGLvJ
      - ZXvRriwSMpEidbM4E
      - b8i6PkgHkEfsjJ7uN
      - 4iyZdsK3HiRFWYcdi
      - 7QscstLbRakw44Wwv
      - 6bzoJXgwpMBrHLAxH
      - d8g6RFXEof6HrRm3g
      - Js7We2E3L9h8WHbTG
      - tPTgyDJuhEMqPfMcK
      - 5SpR3Kt6gjPX3zHLc
      - J5jNLC9t5qCucCsYr
      - mRAjBBhgpWThngkRH
      - wet8mjby3Yb7a6EQW
      - BYeSsSwkoAHyh6tJb
      - ZATTb3q7sXwZDzmM3
      - Kx8eQvgmXphXMC9LD
  - name: 4players_continuous
    factorIds:
      - 3rBswLaaDosuk8nBx
      - Z8qTZzDedy9mqYYhY
      - ArL63u3q64JMufmWJ
      - TBiHZfwFejWkukJfc
      - qtgWqpEtizZ4SKF5C
      - 8xBkmBYw37fmy9Ztb
      - AAXBytkKFMDyadCH9
      - oWBpWDi7Bp2MysKkg
      - HtyBPSwcDcFZiGLvJ
      - ZXvRriwSMpEidbM4E
      - b8i6PkgHkEfsjJ7uN
      - 4iyZdsK3HiRFWYcdi
      - 7QscstLbRakw44Wwv
      - 6bzoJXgwpMBrHLAxH
      - qGAvofMccGriujk7W
      - Js7We2E3L9h8WHbTG
      - tPTgyDJuhEMqPfMcK
      - HTKGopgcALJEYQHCN
      - Y4rcCFqgitz7TJhph
      - JxuySZqk2vstcc78p
      - ZLGoKtfdA23EGw7Y3
      - ZATTb3q7sXwZDzmM3
      - Kx8eQvgmXphXMC9LD
factorTypes:
  - _id: QLen9pcMK75ohbBub
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: sToqhgYZPejDWvsp9
    name: nRounds
    description: number of round
    required: true
    type: Integer
    min: 0
  - _id: wz7s4ufXj2ss5hHGY
    name: randomizeTask
    description: Randomize task
    required: false
    type: Boolean
  - _id: GCGbdjiqFbsHYAYSk
    name: feedback
    description: Feedback
    required: false
    type: Boolean
  - _id: iw8PeJ2CMPbzWhjjZ
    name: feedbackDuration
    description: Feedback duration
    required: false
    type: Number
  - _id: TiwWcki7aj5rS7PvN
    name: responseDuration
    description: Response stage duration in seconds
    required: true
    type: Integer
    min: 1
    max: 1000000000000000
  - _id: yyF4hBsuajGDxxfYP
    name: taskType
    description: >-
      Should be a comma-separated list of task types to use. If not given, all
      task types will be used.
    required: false
    type: String
  - _id: hYW2mT46onSdYX7ds
    name: basePay
    description: >-
      The base amount of money (in USD) a user will get from completing the
      experiment.
    required: false
    type: Number
    min: 0
    max: 10000
  - _id: yfzad3ndbNLQvp8BA
    name: conversionRate
    description: >-
      The conversion rate of score to bonus dollars paid: points x
      conversionRate = bonus in USD.
    required: false
    type: Number
    min: 0
    max: 100000
  - _id: YMa7vmBFmum5YcHX4
    name: longTermEngagement
    description: >-
      For conditions that don’t require synchronized gameplay between multiple
      users/clients; determines whether an additional stage will be added to the
      end of each round with maximum/infinite duration, allowing users to leave
      and return to the page at their convenience.
    required: false
    type: Boolean
  - _id: pGbLrSrHZAatHoC9K
    name: quitEarly
    description: >-
      If toggled, a subject has the option to skip to the Exit Steps prior to
      starting a new round.
    required: false
    type: Boolean
  - _id: KPaBsT8QA6WWc8osT
    name: hints
    description: >-
      Determines what percentage of players will receive hints for their
      questions. This is a JSON map for player index to an array of hint indexes
      that describes exactly which hints are available to which player.  If a
      player is not defined they have no hints.  If no hints are defined at all,
      all players see all hints.      If you want to a random selection of hints
      (no doubles), put a "?" (with the quotation marks) instead of a number.
      E.g. { "1": [1,2], "2": [2,3], "4": [2, "?"]...}.
    required: false
    type: String
  - _id: nB5HyfYmdxKQzWkyi
    name: revealHints
    description: Allows to set the hints as directly revealed.
    required: false
    type: Boolean
  - _id: LqbnLgDHgJzprHbAR
    name: chat
    description: >-
      Determines whether or not you can chat with your neighbors during the
      interactive stage.
    required: true
    type: Boolean
  - _id: mJ3zD5ewQTKtQDmhh
    name: interactionMode
    description: >-
      Determines what kind of interactions the user will be capable of. This
      will either be continuous (each player will be able to see their
      neighbors’ real-time changes) or discreet (players will only be allowed to
      see their neighbors’ guesses after the stage is done).
    required: true
    type: String
    min: 1
    max: 999999
  - _id: e2qdsQ7BTpB32kX5j
    name: networkStructure
    description: >-
      For multiplayer, Determine who is connected to who. I.e.,
      "1-2,1-3,2-5,2-6"
    required: false
    type: String
    min: 1
    max: 999999999999
  - _id: 2cYukeq3bvgZb8Qa6
    name: socialDuration
    description: Social stage duration in seconds
    required: false
    type: Integer
    min: 1
    max: 999999999
  - _id: u6Gc6NvGLnZX57cKg
    name: meanSocialInfo
    description: Show mean value of neighbors on social exposure
    required: false
    type: Boolean
  - _id: SfuTi4jrjoJKeNj8m
    name: minSocialInfo
    description: Show min value of neighbors on social exposure
    required: false
    type: Boolean
  - _id: JTYhugFFkpcQt794j
    name: maxSocialInfo
    description: Show max value of neighbors on social exposure
    required: false
    type: Boolean
  - _id: obi4tgdNS3xNAEiBc
    name: medianSocialInfo
    description: Show median value of neighbor on social exposure
    required: false
    type: Boolean
  - _id: HqQepyditiFfBdzH6
    name: nInteractions
    description: >-
      Determines how many interactive stages there will be. This means there
      will be nInteractions separate stages where players will be able to see
      their neighbors’ guesses.

      This has to be set to 0 for a solo game or a game with continuous social
      interaction.
    required: true
    type: Integer
    min: 0
    max: 99999999
  - _id: g26DS57dNWkaMiRcp
    name: hideSocialNumeric
    description: >-
      If set to false show numeric information about your neighbors’ individual
      guesses. If set to true, don't show. This does not affect whether chats
      are shown or not.
    required: false
    type: Boolean
  - _id: 4Mc2N6mo29A78JWXD
    name: chatGroups
    description: >-
      players are in multiple chat groups (denoted by a letter):
      1-A,1-B,2-B,3-B,4-A,... (1 has 2 chat windows, can talk with 2 and 3 in
      window B, and with 4 in window A).
    required: false
    type: String
    min: 1
    max: 999999999999
  - _id: b48q4W96daDbt4Gmd
    name: hideAvatar
    description: 'If this is set to true, it will hide the players'' avatar during the game.'
    required: false
    type: Boolean
  - _id: 8faqAbLdQx7La6C7u
    name: hideTimer
    description: >-
      If this is set to true, it will hide the timer in all the stages of the
      game except the tutorial.
    required: false
    type: Boolean
factors:
  - _id: ArL63u3q64JMufmWJ
    name: 'true'
    value: true
    factorTypeId: wz7s4ufXj2ss5hHGY
  - _id: tJorWDFxbXwEFSrf7
    name: 'false'
    value: false
    factorTypeId: wz7s4ufXj2ss5hHGY
  - _id: TBiHZfwFejWkukJfc
    name: 'true'
    value: true
    factorTypeId: GCGbdjiqFbsHYAYSk
  - _id: jm9K2nxETRmXhapeL
    name: 'false'
    value: false
    factorTypeId: GCGbdjiqFbsHYAYSk
  - _id: TGWHdjXXjZLwccjdw
    name: 'true'
    value: true
    factorTypeId: YMa7vmBFmum5YcHX4
  - _id: ZXvRriwSMpEidbM4E
    name: 'false'
    value: false
    factorTypeId: YMa7vmBFmum5YcHX4
  - _id: xL3AGrYLngXBjWxqp
    name: 'true'
    value: true
    factorTypeId: pGbLrSrHZAatHoC9K
  - _id: b8i6PkgHkEfsjJ7uN
    name: 'false'
    value: false
    factorTypeId: pGbLrSrHZAatHoC9K
  - _id: 7QscstLbRakw44Wwv
    name: 'true'
    value: true
    factorTypeId: nB5HyfYmdxKQzWkyi
  - _id: 7y2CyWTDkxnAoqtkf
    name: 'false'
    value: false
    factorTypeId: nB5HyfYmdxKQzWkyi
  - _id: 6bzoJXgwpMBrHLAxH
    name: 'true'
    value: true
    factorTypeId: LqbnLgDHgJzprHbAR
  - _id: ATohyGKDQCwhPKT9M
    name: 'false'
    value: false
    factorTypeId: LqbnLgDHgJzprHbAR
  - _id: 5SpR3Kt6gjPX3zHLc
    name: 'true'
    value: true
    factorTypeId: u6Gc6NvGLnZX57cKg
  - _id: ZLGoKtfdA23EGw7Y3
    name: 'false'
    value: false
    factorTypeId: u6Gc6NvGLnZX57cKg
  - _id: J5jNLC9t5qCucCsYr
    name: 'true'
    value: true
    factorTypeId: SfuTi4jrjoJKeNj8m
  - _id: JxuySZqk2vstcc78p
    name: 'false'
    value: false
    factorTypeId: SfuTi4jrjoJKeNj8m
  - _id: HTKGopgcALJEYQHCN
    name: 'true'
    value: true
    factorTypeId: JTYhugFFkpcQt794j
  - _id: mRAjBBhgpWThngkRH
    name: 'false'
    value: false
    factorTypeId: JTYhugFFkpcQt794j
  - _id: Y4rcCFqgitz7TJhph
    name: 'true'
    value: true
    factorTypeId: obi4tgdNS3xNAEiBc
  - _id: wet8mjby3Yb7a6EQW
    name: 'false'
    value: false
    factorTypeId: obi4tgdNS3xNAEiBc
  - _id: hJpuLTkeZsmNhGPy8
    name: 'true'
    value: true
    factorTypeId: g26DS57dNWkaMiRcp
  - _id: ZATTb3q7sXwZDzmM3
    name: 'false'
    value: false
    factorTypeId: g26DS57dNWkaMiRcp
  - _id: MK4BsF4sh3EPEnpJm
    name: 'true'
    value: true
    factorTypeId: b48q4W96daDbt4Gmd
  - _id: DopDgQWuddJgjj5aT
    name: 'false'
    value: false
    factorTypeId: b48q4W96daDbt4Gmd
  - _id: LQrxjCRRJG26s6eex
    name: 'true'
    value: true
    factorTypeId: 8faqAbLdQx7La6C7u
  - _id: fz6T3avpbjyawYpyg
    name: 'false'
    value: false
    factorTypeId: 8faqAbLdQx7La6C7u
  - _id: YWwosMevTALbyZmjc
    name: '1'
    value: 1
    factorTypeId: QLen9pcMK75ohbBub
  - _id: Z8qTZzDedy9mqYYhY
    name: '5'
    value: 5
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: Sqr54q2XogC8senCu
    name: '10'
    value: 10
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: qtgWqpEtizZ4SKF5C
    name: 30s
    value: 30
    factorTypeId: iw8PeJ2CMPbzWhjjZ
  - _id: 8xBkmBYw37fmy9Ztb
    name: 30s
    value: 30
    factorTypeId: TiwWcki7aj5rS7PvN
  - _id: HtyBPSwcDcFZiGLvJ
    name: 1to1
    value: 1
    factorTypeId: yfzad3ndbNLQvp8BA
  - _id: oWBpWDi7Bp2MysKkg
    name: 1USD
    value: 1
    factorTypeId: hYW2mT46onSdYX7ds
  - _id: AAXBytkKFMDyadCH9
    name: geopolitics_daily_life_facts
    value: 'geopolitics,daily_life_facts'
    factorTypeId: yyF4hBsuajGDxxfYP
  - _id: 4iyZdsK3HiRFWYcdi
    name: somehints
    value: '{ "1": [1,2], "2": [2,3], "4": [2]}'
    factorTypeId: KPaBsT8QA6WWc8osT
  - _id: AtNbG3cX6WPS5gRQY
    name: '45'
    value: 45
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: p6nwB2WcgooiR5f7b
    name: '3'
    value: 3
    factorTypeId: QLen9pcMK75ohbBub
  - _id: d8g6RFXEof6HrRm3g
    name: discreet
    value: discreet
    factorTypeId: mJ3zD5ewQTKtQDmhh
  - _id: 3BvaoebRSHSMNnSYE
    name: continous
    value: continous
    factorTypeId: mJ3zD5ewQTKtQDmhh
    archivedAt: 2021-02-03T05:12:58.454Z
  - _id: qGAvofMccGriujk7W
    name: continuous
    value: continuous
    factorTypeId: mJ3zD5ewQTKtQDmhh
  - _id: tPTgyDJuhEMqPfMcK
    name: 30s
    value: 30
    factorTypeId: 2cYukeq3bvgZb8Qa6
  - _id: BYeSsSwkoAHyh6tJb
    name: 3x
    value: 3
    factorTypeId: HqQepyditiFfBdzH6
  - _id: n9JLgRZHaaxmG5pva
    name: 3players
    value: '"1-A,1-B,2-B,3-B,2-A"'
    factorTypeId: 4Mc2N6mo29A78JWXD
    archivedAt: 2021-02-04T15:36:43.844Z
  - _id: dkpPXNPMWngjRc5jr
    name: 3players
    value: '1-2,1-3,2-3,'
    factorTypeId: e2qdsQ7BTpB32kX5j
    archivedAt: 2021-02-04T15:37:33.668Z
  - _id: tz95WfetfCbBPhpqw
    name: 3players
    value: '1-A,1-B,2-B,3-B,2-A'
    factorTypeId: 4Mc2N6mo29A78JWXD
  - _id: iQFwSueW7AupfFpGu
    name: 3players
    value: '1-2,1-3,2-3'
    factorTypeId: e2qdsQ7BTpB32kX5j
  - _id: 3rBswLaaDosuk8nBx
    name: '4'
    value: 4
    factorTypeId: QLen9pcMK75ohbBub
  - _id: Js7We2E3L9h8WHbTG
    name: 4players
    value: '1-2,1-3,2-4,3-4'
    factorTypeId: e2qdsQ7BTpB32kX5j
  - _id: Kx8eQvgmXphXMC9LD
    name: 4players
    value: '1-A,1-B,2-B,3-B,2-A,4-A'
    factorTypeId: 4Mc2N6mo29A78JWXD
  - _id: Z2WCnquEqT8cgLPS6
    name: '0'
    value: 0
    factorTypeId: HqQepyditiFfBdzH6
  - _id: TENHMfaczicNzmg9S
    name: infinite
    value: 1000000000000000
    factorTypeId: TiwWcki7aj5rS7PvN
  - _id: qJ3QCatryHYSpftgr
    name: 60s
    value: 60
    factorTypeId: TiwWcki7aj5rS7PvN
  - _id: pbqwnTgBQhx9FzDfW
    name: 60s
    value: 60
    factorTypeId: 2cYukeq3bvgZb8Qa6
  - _id: TGbh4iGEMRRSeHroG
    name: infinite
    value: 999999999
    factorTypeId: 2cYukeq3bvgZb8Qa6
  - _id: 6LKHhcrgaobuZHc3w
    name: '1000'
    value: 1000
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: zJHnkk3JCztzdSRi5
    name: '2'
    value: 2
    factorTypeId: QLen9pcMK75ohbBub
  - _id: D9qMBf82gvLE2ELwi
    name: '5'
    value: 5
    factorTypeId: QLen9pcMK75ohbBub
  - _id: kJssnFKKFNHTbF5aN
    name: '6'
    value: 6
    factorTypeId: QLen9pcMK75ohbBub
  - _id: oHBHCPYWSB5wzsXov
    name: '7'
    value: 7
    factorTypeId: QLen9pcMK75ohbBub
  - _id: hNsz7jhMuFn42D2Bj
    name: '8'
    value: 8
    factorTypeId: QLen9pcMK75ohbBub
  - _id: RHj5tcYbpQeFAkden
    name: '9'
    value: 9
    factorTypeId: QLen9pcMK75ohbBub
  - _id: iNCPvibFdrQeN9yjx
    name: '10'
    value: 10
    factorTypeId: QLen9pcMK75ohbBub
  - _id: ZaHvuL44GmanwuqoF
    name: 1random
    value: '{"1":["?"]}'
    factorTypeId: KPaBsT8QA6WWc8osT
lobbyConfigs:
  - name: Default
    timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: fail
    gameLobbyIds: []
  - name: NeverFail
    timeoutType: lobby
    timeoutInSeconds: 3600000
    timeoutStrategy: fail
    gameLobbyIds: []
