treatments:
  - name: solo 5 feedback long
    factorIds:
      - YWwosMevTALbyZmjc
      - Z8qTZzDedy9mqYYhY
      - JRFdTGEFggbqX5KmX
      - jroGer53RuC45SK4D
      - qtgWqpEtizZ4SKF5C
      - 8xBkmBYw37fmy9Ztb
      - oWBpWDi7Bp2MysKkg
      - HtyBPSwcDcFZiGLvJ
      - kkMvHy4TPDWLXR4yQ
      - i9BTjcKPJZPPupFzp
      - 4iyZdsK3HiRFWYcdi
factorTypes:
  - _id: f2kFS6kvXozvzBKRH
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: sToqhgYZPejDWvsp9
    name: nRounds
    description: number of round
    required: true
    type: Integer
    min: 0
  - _id: wz7s4ufXj2ss5hHGY
    name: randomizeTask
    description: Randomize task
    required: false
    type: Boolean
  - _id: GCGbdjiqFbsHYAYSk
    name: feedback
    description: Feedback
    required: false
    type: Boolean
  - _id: iw8PeJ2CMPbzWhjjZ
    name: feedbackDuration
    description: Feedback duration
    required: false
    type: Number
  - _id: TiwWcki7aj5rS7PvN
    name: responseDuration
    description: Response stage duration in seconds
    required: true
    type: Integer
    min: 1
    max: 1000000000000000
  - _id: yyF4hBsuajGDxxfYP
    name: taskType
    description: >-
      Should be a comma-separated list of task types to use. If not given, all
      task types will be used.
    required: false
    type: String
  - _id: hYW2mT46onSdYX7ds
    name: basePay
    description: >-
      The base amount of money (in USD) a user will get from completing the
      experiment.
    required: false
    type: Number
    min: 0
    max: 10000
  - _id: yfzad3ndbNLQvp8BA
    name: conversionRate
    description: >-
      The conversion rate of score to bonus dollars paid: points x
      conversionRate = bonus in USD.
    required: false
    type: Number
    min: 0
    max: 100000
  - _id: YMa7vmBFmum5YcHX4
    name: longTermEngagement
    description: >-
      For conditions that don’t require synchronized gameplay between multiple
      users/clients; determines whether an additional stage will be added to the
      end of each round with maximum/infinite duration, allowing users to leave
      and return to the page at their convenience.
    required: false
    type: Boolean
  - _id: pGbLrSrHZAatHoC9K
    name: quitEarly
    description: >-
      If toggled, a subject has the option to skip to the Exit Steps prior to
      starting a new round.
    required: false
    type: Boolean
  - _id: KPaBsT8QA6WWc8osT
    name: hints
    description: >-
      Determines what percentage of players will receive hints for their
      questions. This is a JSON map for player index to an array of hint indexes
      that describes exactly which hints are available to which player.  If a
      player is not defined they have no hints.  If no hints are defined at all,
      all players see all hints.      If you want to a random selection of hints
      (no doubles), put a "?" (with the quotation marks) instead of a number.
      E.g. { "1": [1,2], "2": [2,3], "4": [2, "?"]...}.
    required: false
    type: String
  - _id: nB5HyfYmdxKQzWkyi
    name: revealHints
    description: Allows to set the hints as directly revealed.
    required: false
    type: Boolean
  - _id: b48q4W96daDbt4Gmd
    name: hideAvatar
    description: 'If this is set to true, it will hide the players'' avatar during the game.'
    required: false
    type: Boolean
  - _id: 8faqAbLdQx7La6C7u
    name: hideTimer
    description: >-
      If this is set to true, it will hide the timer in all the stages of the
      game except the tutorial.
    required: false
    type: Boolean
  - _id: dpr3vjHMt2pTHjywC
    name: shuffleHints
    description: >-
      If this is true, the player index will be shuffled so that the
      players always receive the same position of hint (the 1st, 2nd, or 3rd,
      etc.) for each task, but which position of hint they receive is random at
      first.
    required: false
    type: Boolean
factors:
  - _id: JRFdTGEFggbqX5KmX
    name: 'true'
    value: true
    factorTypeId: wz7s4ufXj2ss5hHGY
  - _id: MgmZcGRbhcT8obfBR
    name: 'false'
    value: false
    factorTypeId: wz7s4ufXj2ss5hHGY
  - _id: jroGer53RuC45SK4D
    name: 'true'
    value: true
    factorTypeId: GCGbdjiqFbsHYAYSk
  - _id: hxX9kQr2aG9pFCJxy
    name: 'false'
    value: false
    factorTypeId: GCGbdjiqFbsHYAYSk
  - _id: kkMvHy4TPDWLXR4yQ
    name: 'true'
    value: true
    factorTypeId: YMa7vmBFmum5YcHX4
  - _id: fNujPCT2T9tBJHjae
    name: 'false'
    value: false
    factorTypeId: YMa7vmBFmum5YcHX4
  - _id: i9BTjcKPJZPPupFzp
    name: 'true'
    value: true
    factorTypeId: pGbLrSrHZAatHoC9K
  - _id: PkBhE6BPdi6BKSQZi
    name: 'false'
    value: false
    factorTypeId: pGbLrSrHZAatHoC9K
  - _id: cqDztrwmRTTzqEG3E
    name: 'true'
    value: true
    factorTypeId: nB5HyfYmdxKQzWkyi
  - _id: N4c6mXPCrBTjHkzeN
    name: 'false'
    value: false
    factorTypeId: nB5HyfYmdxKQzWkyi
  - _id: wvSxkWQzxprMtpsGL
    name: 'true'
    value: true
    factorTypeId: b48q4W96daDbt4Gmd
  - _id: kpTrWRQn4axpcdgsa
    name: 'false'
    value: false
    factorTypeId: b48q4W96daDbt4Gmd
  - _id: g8cZvLubsKyKWXyoP
    name: 'true'
    value: true
    factorTypeId: 8faqAbLdQx7La6C7u
  - _id: XqnxwtbYBZDS6rG2E
    name: 'false'
    value: false
    factorTypeId: 8faqAbLdQx7La6C7u
  - _id: YWwosMevTALbyZmjc
    name: '1'
    value: 1
    factorTypeId: f2kFS6kvXozvzBKRH
  - _id: Z8qTZzDedy9mqYYhY
    name: '5'
    value: 5
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: Sqr54q2XogC8senCu
    name: '10'
    value: 10
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: qtgWqpEtizZ4SKF5C
    name: 30s
    value: 30
    factorTypeId: iw8PeJ2CMPbzWhjjZ
  - _id: 8xBkmBYw37fmy9Ztb
    name: 30s
    value: 30
    factorTypeId: TiwWcki7aj5rS7PvN
  - _id: HtyBPSwcDcFZiGLvJ
    name: 1to1
    value: 1
    factorTypeId: yfzad3ndbNLQvp8BA
  - _id: oWBpWDi7Bp2MysKkg
    name: 1USD
    value: 1
    factorTypeId: hYW2mT46onSdYX7ds
  - _id: AAXBytkKFMDyadCH9
    name: geopolitics_daily_life_facts
    value: 'geopolitics,daily_life_facts'
    factorTypeId: yyF4hBsuajGDxxfYP
  - _id: 4iyZdsK3HiRFWYcdi
    name: somehints
    value: '{ "1": [1,2], "2": [2,3], "4": [2]}'
    factorTypeId: KPaBsT8QA6WWc8osT
  - _id: AtNbG3cX6WPS5gRQY
    name: '45'
    value: 45
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: bZ7CAPYhYGZZgvA6N
    name: '999999999'
    value: 999999999
    factorTypeId: sToqhgYZPejDWvsp9
  - _id: YGyrZQhE6azy6h4cE
    name: 1random
    value: '{"1":["?"]}'
    factorTypeId: KPaBsT8QA6WWc8osT
  - _id: LcbQRDy4gGu4MHXe3
    name: 10x1
    value: >-
      {     "1": [         1     ],     "2": [         2     ],     "3":
      [         3     ],     "4": [         4     ],     "5": [         5    
      ],     "6": [         6     ],     "7": [         7     ],     "8":
      [         8     ],     "9": [         9     ],     "10": [         10    
      ] }
    factorTypeId: KPaBsT8QA6WWc8osT
  - _id: 9HdLoXxTKLoK3ZNuX
    name: 'true'
    value: true
    factorTypeId: dpr3vjHMt2pTHjywC
  - _id: DCtqDn3N3j8dPSy37
    name: 'false'
    value: false
    factorTypeId: dpr3vjHMt2pTHjywC
lobbyConfigs:
  - name: Default
    timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: fail
    gameLobbyIds: []
  - name: NeverFail
    timeoutType: lobby
    timeoutInSeconds: 3600000
    timeoutStrategy: fail
    gameLobbyIds: []
